//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stone
    {
        public int? Id { get; set; }
        public string Stone_Name { get; set; }
        public double? Cord_Price { get; set; }
        public double? Amount_of_Stone { get; set; }
        public double? Price_per_Stone { get; set; }
        public int? Diameter_of_Stone { get; set; }
        public string Faceting { get; set; }
        public string Store { get; set; }
    }
}
